server:
  # 服务器Http端口，默认 8080
  port: 8080
  servlet:
    # 应用访问路径，默认 /
    context-path: /

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  # jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
